#%RAML 1.0 DataType 
type: object
properties:
  account_type:
    type: string
    required: false
  account_number:
    type: string
    required: false
  currency:
    type: string
    required: false
  initial_balance:
    type: integer
    required: false
