#%RAML 1.0 DataType 
type: object
properties:
  customerId:
    type: string
    required: false
  name:
    type: string
    required: false
  phoneNumber:
    type: string
    required: false
  email:
    type: string
    required: false
  address:
    type: string
    required: false
  age:
    type: string
    required: false
  balance:
    type: string
    required: false


